Add go fmt test.

diff --git a/software/earl/Makefile b/software/earl/Makefile
--- a/software/earl/Makefile
+++ b/software/earl/Makefile
@@ -7,7 +7,11 @@ BUILDDATE ?= $(shell date --iso-8601=seconds)
 REVISION  ?= $(shell git rev-parse HEAD)
 VERSION   ?= $(shell git log --date=short --pretty=format:'%h@%cd' -n 1 .)
 
-all : earl test
+GO        ?= go
+GOFMT     ?= $(GO)fmt
+
+
+all: style earl test
 
 earl: *.go
 	go build -ldflags "-X main.Branch=$(BRANCH) -X main.BuildDate=$(BUILDDATE) -X main.Revision=$(REVISION) -X main.Version=$(VERSION)"
@@ -22,3 +26,12 @@ install:
 	install init.d/earl /etc/init.d/earl
 	install earl /usr/local/bin/earl
 	update-rc.d earl defaults
+
+style:
+	@echo ">> checking code style"
+	@fmtRes=$$($(GOFMT) -d $$(find . -path ./vendor -prune -o -name '*.go' -print)); \
+	if [ -n "$${fmtRes}" ]; then \
+		echo "gofmt checking failed!"; echo "$${fmtRes}"; echo; \
+		echo "Please ensure you are using $$($(GO) version) for formatting code."; \
+		exit 1; \
+	fi
